#!/bin/bash

### BEGIN INIT INFO
# Provides:          
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: daemon startup script lojaMobioh
# Description:       lojamobioh
### END INIT INFO

MOBIOH_HOME_DIR=/mobioh/programas/service
MOBIOH_HOME_JAR=/mobioh/programas/bin
MOBIOH_JAVA_HOME=/mobioh/programas/java/bin
MOBIOH_LOG=/mobioh/programas/var/log
export MOBIOH_HOME=/mobioh/

case "$1" in
 start)
	$MOBIOH_JAVA_HOME/java -jar $MOBIOH_HOME_JAR/loja.jar &
	PID=$(netstat -antp | grep 8586 | head -n1 | awk {'print $7'} | cut -d/ -f1)
	echo $PID > $MOBIOH_HOME_DIR/pid
 ;;

 stop)
	kill -9 $(netstat -antp | grep 8586 | head -n1 | awk {'print $7'} | cut -d/ -f1)
 ;;

 restart)
	kill -9 $(netstat -antp | grep 8586 | head -n1 | awk {'print $7'} | cut -d/ -f1)
	$MOBIOH_JAVA_HOME/java -jar $MOBIOH_HOME_JAR/loja.jar &
 ;;
 *)
	service lojaservice start
 ;;
esac
